# Generated by Django 6.0 on 2026-01-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_material',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Material ID'),
        ),
    ]
