# Generated by Django 6.0 on 2026-01-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_materials', '0002_alter_material_id_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Material Type Name')),
                ('symbol', models.CharField(blank=True, max_length=250, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
                'db_table': 'material_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Unit Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Unit Measure',
                'verbose_name_plural': 'Unit Measures',
                'db_table': 'unit_measures',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='status',
        ),
        migrations.RemoveField(
            model_name='material',
            name='unit',
        ),
    ]
