# Generated by Django 6.0 on 2026-01-22 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
        ('app_materials', '0003_materialtype_unitmeasure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_materials.materialtype', verbose_name='Material Type'),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_core.status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_materials.unitmeasure', verbose_name='Unit Measure'),
        ),
    ]
