# Generated by Django 6.0 on 2026-01-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='accounting',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Create and modify')], default='0'),
        ),
        migrations.AlterField(
            model_name='role',
            name='customers',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Create and modify')], default='0'),
        ),
        migrations.AlterField(
            model_name='role',
            name='inventory',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Create and modify')], default='0'),
        ),
        migrations.AlterField(
            model_name='role',
            name='materials',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Create and modify')], default='0'),
        ),
        migrations.AlterField(
            model_name='role',
            name='purchases',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Create and modify')], default='0'),
        ),
        migrations.AlterField(
            model_name='role',
            name='reporting',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Create and modify')], default='0'),
        ),
        migrations.AlterField(
            model_name='role',
            name='sales',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Create and modify')], default='0'),
        ),
        migrations.AlterField(
            model_name='role',
            name='suppliers',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Create and modify')], default='0'),
        ),
    ]
