# Generated by Django 6.0 on 2026-01-17 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_supplier', models.CharField(max_length=50, unique=True, verbose_name='Supplier ID')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='Legal Name')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('tax_id', models.CharField(max_length=30, verbose_name='Tax ID')),
                ('country', models.CharField(max_length=60, verbose_name='Country')),
                ('state_province', models.CharField(max_length=60, verbose_name='State/Province')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('zip_code', models.IntegerField(verbose_name='ZIP Code')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Contact Person')),
                ('contact_role', models.CharField(max_length=150, verbose_name='Contact Role')),
                ('category', models.CharField(max_length=150, verbose_name='Category')),
                ('payment_terms', models.CharField(max_length=150, verbose_name='Payment Terms')),
                ('currency', models.CharField(max_length=50, verbose_name='Currency')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Payment Method')),
                ('bank_account', models.CharField(max_length=150, verbose_name='Bank Account')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
    ]
